name: rain-stats-scripts
channels:
  - bioconda
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bcbio-gff=0.7.1=pyh7e72e81_2
  - biopython=1.85=py312h66e93f0_1
  - bx-python=0.13.0=py312h5e9d817_1
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2025.7.14=hbd8a1cb_0
  - frozendict=2.4.6=py312h66e93f0_0
  - ld_impl_linux-64=2.43=h712a8e2_4
  - libblas=3.9.0=31_h59b9bed_openblas
  - libcblas=3.9.0=31_he106b2a_openblas
  - libexpat=2.7.0=h5888daf_0
  - libffi=3.4.6=h2dba641_1
  - libgcc=14.2.0=h767d61c_2
  - libgcc-ng=14.2.0=h69a702a_2
  - libgfortran=14.2.0=h69a702a_2
  - libgfortran5=14.2.0=hf1ad2bd_2
  - libgomp=14.2.0=h767d61c_2
  - liblapack=3.9.0=31_h7ac8fdf_openblas
  - liblzma=5.8.1=hb9d3cd8_0
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.29=pthreads_h94d23a6_0
  - libsqlite=3.49.1=hee588c1_2
  - libstdcxx=14.2.0=h8f9b012_2
  - libstdcxx-ng=14.2.0=h4852527_2
  - libunwind=1.6.2=h9c3ff4c_0
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - natsort=8.4.0=pyh29332c3_1
  - ncurses=6.5=h2d0b736_3
  - numpy=2.2.4=py312h72c5963_0
  - openssl=3.5.1=h7b32b05_0
  - pip=25.0.1=pyh8b19718_0
  - progressbar2=4.5.0=pyhd8ed1ab_1
  - py-spy=0.4.0=h4c5a871_1
  - pyparsing=3.2.3=pyhd8ed1ab_1
  - python=3.12.10=h9e4cc4f_0_cpython
  - python-utils=3.9.1=pyhff2d567_1
  - python_abi=3.12=6_cp312
  - readline=8.2=h8c095d6_2
  - setuptools=78.1.0=pyhff2d567_0
  - six=1.17.0=pyhd8ed1ab_0
  - sortedcontainers=2.4.0=pyhd8ed1ab_1
  - tk=8.6.13=noxft_h4845f30_101
  - typing_extensions=4.13.2=pyh29332c3_0
  - tzdata=2025b=h78e105d_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - pysam=0.23.3=py312h47d5410_1
  - pandas
  - pip:
      - flameprof==0.4
prefix: /home/earx/miniforge3/envs/rain-stats-scripts
